#!/bin/bash

echo "🚀 Portfolio Deployment Guide"
echo "================================"
echo ""
echo "Your portfolio is ready to deploy!"
echo ""
echo "📁 Project Structure:"
echo "   - Frontend: /app/frontend"
echo "   - Build: /app/frontend/build (production-ready)"
echo ""
echo "🌐 Deployment Options:"
echo ""
echo "Option 1: GitHub + Vercel (Recommended)"
echo "=========================================="
echo "1. Create a GitHub repository at: https://github.com/new"
echo "   Name: portfolio-website"
echo ""
echo "2. Run these commands in your terminal:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial portfolio commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR-USERNAME/portfolio-website.git"
echo "   git push -u origin main"
echo ""
echo "3. Deploy on Vercel:"
echo "   - Go to: https://vercel.com"
echo "   - Sign up with GitHub"
echo "   - Click 'Import Project'"
echo "   - Select your portfolio-website repo"
echo "   - Root Directory: frontend"
echo "   - Click Deploy"
echo ""
echo "Option 2: Direct Deploy with Vercel CLI"
echo "=========================================="
echo "1. Install Vercel CLI:"
echo "   npm install -g vercel"
echo ""
echo "2. Deploy:"
echo "   cd /app/frontend"
echo "   vercel"
echo ""
echo "Option 3: Netlify Drop"
echo "======================="
echo "1. Build is ready at: /app/frontend/build"
echo "2. Go to: https://app.netlify.com/drop"
echo "3. Drag the 'build' folder"
echo "4. Done!"
echo ""
echo "✅ Your portfolio will be live in minutes!"
echo ""
